### ISSUE TITLE
Relax the dune dependency check for opam-file-format

### ISSUE THREAD

**Issue by dra27** [ocurrent/opam-dune-lint#12]
Greetings from the one tedious opam package which has Dune as a depopt!

opam-dune-lint is upset (I think) at the lack of `"dune"` in `depends:` in [this run for opam-file-format](https://ci.ocamllabs.io/github/ocaml/opam-file-format/commit/1b77ccb1d72aa981219628ba8a93deb03555986c/variant/(lint-opam)).

Could that check be ignored if the package is listed in depopts? Sorry for yet another annoying special case for opam-file-format!

**Comment by talex5** [comment]
Yeah, depopts is obviously something it should support (although the idea of a conditional dependency on dune is a bit :scream:).

**Comment by dra27** [comment]
I hope that opam-file-format remains unique in needing it! Although there are packages like cmdliner which could be specified that way too
