### ISSUE TITLE
version string

### ISSUE THREAD

**Issue by hannesm** [ocurrent/opam-dune-lint#19]
hey,

thanks for this piece of code (and running it in ocaml-ci). I would appreciate some slightly adapted output. at the moment, the output is:
```
"lwt" {>= 4.2.0}
```

while in an opam file the following is expected:
```
"lwt" {>= "4.2.0"}
```

would be great to include `"` around the version number, for easier copy & paste from tool output to opam file.

**Comment by talex5** [comment]
That's a good idea. But note that you can just do `opam dune-lint` and have the tool do it for you, in the correct format.

**Comment by talex5** [comment]
Fixed by #32.
