### ISSUE TITLE
Dune builtin libraries are not taken into account

### ISSUE THREAD

**Issue by kit-ty-kate** [ocurrent/opam-dune-lint#2]
A number of libraries are defined as builtin in dune itself: https://github.com/ocaml/dune/blob/cd7ea706bc3c56f8bf3bcd979515ddabb84e45e0/src/dune_rules/findlib/meta.ml#L149

Test case:
```
$ cat dune
(library
  (public_name test)
  (libraries threads))
$ cat test.opam
opam-version: "2.0"
depends: [
]
$ touch test.ml
$ dune-opam-lint
Done: 0/0 (jobs: 0)test.opam:directorieses
  "ocamlfind" {>= 1.8.1}
Wrote "./test.opam"
```
In this case ocamlfind is not needed as dune is gonna use the builtin threads module anyway.

**Comment by talex5** [comment]
Ah, OK. It's because the `lib/threads/META` file is created by `ocamlfind`, but it does indeed seem that we can build without it. I'll remove `threads` from the dependencies list.

**Comment by talex5** [comment]
The dune man-page says:

> The output of `dune external-lib-deps @install` should be included in what is written in your `<package>.opam` file.

Perhaps dune should be updated to filter `threads` out itself?

**Comment by kit-ty-kate** [comment]
there are a number of builtin libraries, not just threads. I just used threads as an example. Could this issue be reopened?

**Comment by talex5** [comment]
Shouldn't it be a bug in dune? Dune is telling us this needs to be in the opam file.

**Comment by talex5** [comment]
Anyway, I've enabled cram tests now. Feel free to add any examples of it not working to the tests directory.

**Comment by talex5** [comment]
I've added all the ones I could find in #11. If you know of more, please add them :-)
