### ISSUE TITLE
Add support for correction of uninstalled libraries

### ISSUE THREAD

**Issue by shonfeder** [ocurrent/opam-dune-lint#21]
This tool is fantastic. Thank you!

I think a very nice workflow would be something like the following:

- Add a library dependency to a component's `dune` file.
- Run `opam-dune-lint`, to add the dependency to the `dune-project` file.
- Run `opam install . --deps-only` to install any needed libraries.

This sequence could be added as a single command in editor quite easily, providing pretty seamless dependency management.

However, it looks like `opam-dune-lint` currently fails when a library isn't installed. E.g.,

```lisp
File "bin/dune", line 4, characters 12-15:
4 |  (libraries omd bos))
                ^^^
Error: Library "omd" not found.
Hint: try:
  dune external-lib-deps --missing --display progress @install
Done: 0/0 (jobs: 0)opam-dune-lint: internal error, uncaught exception:
                (Failure
                  "run ['dune' 'build' '--display=progress' '@install']: exited with 1")
```

Would you be open to such a change?

**Comment by talex5** [comment]
There's no way for it to know what package provides a library if the library is not installed.

**Comment by shonfeder** [comment]
Oh, too bad!

I'd hoped that since `dune` itself seems able to to make reasonable guesses in such cases (e.g., in this case, `dune external-lib-deps --missing --display progress @install` correctly suggests `opam install omd`) it might be feasible. But I'm guessing that's too error prone for the purposes of this tool?

**Comment by moyodiallo** [comment]
There is a new release v0. 3 that doesn't use the `dune build..`, so even if there's a Library that is not installed, the lint process won't fail, `dune describe opam-files` replace `dune build`.

This could remain closed, if no suggest.
