### ISSUE TITLE
Check that the dune constraint matches the dune-project file

### ISSUE THREAD

**Issue by kit-ty-kate** [ocurrent/opam-dune-lint#28]
Currently opam-dune-lint does not check for the validity of the dune constraint however this is a desirable feature that would make adding an opam-dune-lint phase to opam-repo-ci desirable in the future (we might want to think about the implications of having every explicit dependencies be listed, first)

Implemented in opam-repo-ci in https://github.com/ocurrent/opam-repo-ci/pull/90. Feel free to copy/paste what's needed.

**Comment by moyodiallo** [comment]
This is fixed, thanks for the indication. Your implementation was very useful, with a slight modification it was OK.
