### ISSUE TITLE
feature request : preserve comments in opam files.

### ISSUE THREAD

**Issue by abate** [ocurrent/opam-dune-lint#37]
Thank you for this tool. It definitely helps.

While linting, `opam-dune-lint` removes comments from the opam file. Would it be possible to preserve these comments ( lines starting with `#` ? ) . This would be very nice. Not sure how difficult is to add this exception in the parser...

Thanks you again !

**Comment by talex5** [comment]
opam-dune-lint just uses opam to read and write the file:

https://github.com/ocurrent/opam-dune-lint/blob/06cb41933c788f81331efdd78bea762935ffe30d/main.ml#L58
https://github.com/ocurrent/opam-dune-lint/blob/06cb41933c788f81331efdd78bea762935ffe30d/main.ml#L121

So, preserving comments would have to be added to opam instead.

**Comment by abate** [comment]
I see. thanks ! I'll open an issue in opam.

**Comment by kit-ty-kate** [comment]
I believe this should be reopened (see comment in the opam issue)

**Comment by talex5** [comment]
Ah, that's useful! I've proposed a fix using it in #40.
