### ISSUE TITLE
feature request : separate linting and fix dependencies.

### ISSUE THREAD

**Issue by abate** [ocurrent/opam-dune-lint#38]
Would it be possible to separate the linting phase from the fixing phase. 

Linting files is great, but if I lint and change dependencies at the same time the review process become a bit more complicated. If I can push two different commits, this become fairly easy.

would it be possible to add a switch to only do linting ?

thank you !

**Comment by talex5** [comment]
Couldn't you just not accept the changes when it prompts you?

But I don't see why you'd want to have a wrong commit followed by a fixed one, when you could have a single correct commit.

**Comment by abate** [comment]
I'm dealing with a project with many of dune and opam files . So running `opam-dune-lint --lint -yes` and accept all linting changes at once without manual intervention would be great for me. This could also be used in the CI to make sure all dune and opam file are correctly formatted. For a single dune/opam project, i agree it's not a killer feature.

After the linting phase adding another commit with only the deps changes ( these are the important changes ) can help the reviewer to see what is actually going to change.

**Comment by talex5** [comment]
The option for that is `--force`, not `-yes`. In summary:
- To always apply changes, use `--force`.
- To never apply changes, run without a tty (e.g. `opam dune-lint < /dev/null`).
- Otherwise, it will ask you to confirm.

**Comment by abate** [comment]
sorry, I think I didn't explain myself. `opam-dune-lint` lint *and* fix dependencies in one go. I'm looking for a way to just either linting or fixing dependencies, but not both at once, as the diff might be big and complicated to read.

maybe I should use another tool to lint and reformat the dune and opam files and the use `opam-dune-lint` just to fix the dependencies ?

**Comment by talex5** [comment]
Ah. It doesn't do any linting except of the dune dependencies. You need plain `opam lint` for that.
