### ISSUE TITLE
feature request: detect superfluous dependencies in opam file

### ISSUE THREAD

**Issue by hannesm** [ocurrent/opam-dune-lint#39]
in some projects, dependencies in the dune file get removed (plus in the OCaml code), but the dependencies in the opam file are untouched. Since opam-dune-lint already has the machinery to know about dune and opam files, it would be great if it could check for superfluous dependencies in the opam files, and suggest to remove them.

**Comment by hannesm** [comment]
see e.g. https://github.com/dinosaure/paf-le-chien/pull/39 and https://github.com/dinosaure/mimic/pull/3 (though the second one is likely much harder to figure out automatically)

**Comment by talex5** [comment]
It's hard to be sure that a dependency isn't needed though. e.g. `conf-libev` modifies the behaviour of lwt, and `conf-graphviz` provides a command to use at runtime (and not all such packages start with `conf-`).

**Comment by hannesm** [comment]
closing: lack of interest and lack of activity here.
