### ISSUE TITLE
incorrect request for adding with-test annotation

### ISSUE THREAD

**Issue by cdaringe** [ocurrent/opam-dune-lint#42]
# Problem

`opam-dune-lint` fails stating:

```
/src: (run (shell "opam exec -- opam-dune-lint"))
hood.opam: changes needed:
  "dune"                                   (remove {with-test})
  "containers" {with-test}                 [from src/lib/hood] (missing {with-test} annotation)
  "ppx_deriving" {with-test}               [from src/lib/hood] (missing {with-test} annotation)
  "ppx_yojson_conv" {with-test}            [from src/lib/hood] (missing {with-test} annotation)
```

# Context

- My workspace has libs/bins/tests
- I use the `containers` & ppx_* libs
- the aforementioned packages should not need to be tagged with `with-test`, per [the opam docs](https://opam.ocaml.org/doc/Packaging.html#The-file-format-in-more-detail)
- opam-dune-lint emits the warning here: per the [https://github.com/ocurrent/opam-dune-lint/blob/aa295f9a0e5e6519ec184c0c932695a740fe8021/main.ml#L108](the report generator)
- [failing lint step here](https://ci.ocamllabs.io/github/cdaringe/my.hood/commit/d6c0a13df378c25929e9abaa28362cc4f4b00724/variant/(lint-opam))
- [opam file here](https://github.com/cdaringe/my.hood/blob/main/hood.opam#L10-L37). fwiw, my project is kind of in a garbage state, so don't look under the hood :)

I suspect there may be an _ordering_ issue at play, here.

**Comment by cdaringe** [comment]
hmm. swapping order made no difference. ya, unclear on why the tool suggests `with-test` is required. this to me suggests that these would only be installed when the flag is passed, when in fact i need them _always_ for my bin and my lib. thus, they are part of the base set of dependencies

**Comment by talex5** [comment]
If you `opam install .` on your package, does it actually install any binaries or libraries? I suspect it doesn't, and so the only thing using these libraries are the tests. Perhaps you need a `(public_name ...)` somewhere?

**Comment by cdaringe** [comment]
Hey @talex5. Thanks for the response!

> does it actually install any binaries or libraries?

Yep, sure does!

```sh
❯ opam switch create . 4.13.1
Package hood does not exist, create as a NEW package? [Y/n] y
hood is now pinned to git+file:///Users/cdaringe/src/my.hood#main (version ~dev)

<><> Installing new switch packages <><><><><><><><><><><><><><><><><><><><>  🐫
Switch invariant: ["ocaml-base-compiler" {= "4.13.1"} | "ocaml-system" {= "4.13.1"}]
The following actions will be performed:
  // snip snip snip
  ∗ install ppx_deriving        5.2.1   [required by hood]
  ∗ install yojson              1.7.0   [required by hood]
  ∗ install containers          3.6.1   [required by hood]
  ∗ install ppx_yojson_conv     v0.14.0 [required by hood]
  ∗ install hood                ~dev*
===== ∗ 30 =====


my.hood on  main via  v16.6.2 via 🐫 v4.13.1 (*my.hood) took 3s
❯ opam list | grep containers
containers          3.6.1       A modular, clean and powerful extension of the OCaml standard library
```

Further, my libraries (not tests) definitely use the deps (such as containers). Thus, I posit that the lint recommendation is still incorrect

**Comment by talex5** [comment]
I mean, what actual executable files or ocamlfind libraries does your package install inside the "hood" package? It looks like it's just an empty package:

```
$ ls ~/.opam/4.13/lib/hood/
META  dune-package  opam
```

If you make the changes suggested by opam-dune-lint, I suspect your package will still install just the same without those dependencies.

**Comment by cdaringe** [comment]
Thank you :)
