### ISSUE TITLE
Support dune 3.0

### ISSUE THREAD

**Issue by smorimoto** [ocurrent/opam-dune-lint#45]

**Comment by booklearner** [comment]
I can start an attempt to do this if it's not already in progress. Feel free to reach out with any tips!

**Comment by talex5** [comment]
That would be great! The changes are mostly needed in dune, however.

Dune removed `external-lib-deps` because it was hard to implement, but this was because it tried to work out the dependencies without building the project first. For opam-dune-lint, that's not a problem.

The dune developers said:

> First step for Dune would be to restore external-lib-deps, but as an output of the build itself (so it would become more precise, but at the cost of doing a build, which is fine).

**Comment by moyodiallo** [comment]
`external-lib-deps` is back for the next release of dune, as `dune describe external-lib-deps`(https://github.com/ocaml/dune/pull/6045). But for the support 3.0, the lib `dune-private-libs.dune-lang` is removed since dune 3.0 and dune-lang is now private in dune.

**Comment by talex5** [comment]
> `external-lib-deps` is back

Great - thanks!

> `dune-private-libs.dune-lang` is removed

Ah. It looks like we just it for modifying the dune-project file with the updated packages. But they're just S-expressions, so we could do it with some other S-expression library. I think they only reason we care about it is to get the right formatting for the output, but perhaps there's a way to make `dune fmt` sort it out afterwards?

**Comment by moyodiallo** [comment]
For formatting dune files, there's a command `dune format-dune-file <file>`. It works for `dune-project` file too. But I don't know if it format the way it's needed in opam-dune-lint.

**Comment by tmcgilchrist** [comment]
@talex5 is right we can just use a simple s-expression library, maybe https://github.com/ocaml-dune/csexp since it has minimal dependencies. Then formatting via `dune format-dune-file <file>` 👍🏻 

Ideally this should all get moved into dune/opam proper as an extra lint command.

**Comment by talex5** [comment]
csexp is a binary(ish) format. https://github.com/janestreet/parsexp is probably what you want.

**Comment by moyodiallo** [comment]
Yes, I confirm we need that lib.

**Comment by moyodiallo** [comment]
The command `dune describe external-lib-deps` has not alias like `@install` or `@runtest`. It prints out all the external dependencies by dir only. Is it a big deal for linting `"with-test"`? Because with this command we won't be able to do that.
https://github.com/ocurrent/opam-dune-lint/blob/fa223083adec698a8c43268a1a1b5b33bafd3722/main.ml#L82-L83

**Comment by moyodiallo** [comment]
Mentioning this PR #46, it's not far from solving the issue.

**Comment by Lupus** [comment]
@moyodiallo it seems that there are only couple stylistic remarks in dune related PRs and those await your input. It's painful to match dependencies between opam and dune by hand, would be really awesome if this could go live!

**Comment by moyodiallo** [comment]
I admit this is a hack, dune doesn't release the necessary libraries. what we have is, printing out from dune (the PRs) the needed information. This is the same approximation as the current version.

**Comment by Lupus** [comment]
By current version you mean the `master` branch? I've just tried installing `opam-dune-lint` via opam and it suggested to downgrade dune.

**Comment by moyodiallo** [comment]
yes the master branch or the lastest release, the downgrade is normal.

**Comment by Lupus** [comment]
We're using dune 3.x, downgrading is not an option, but If I understand this correctly, the PRs in dune repo can unblock use of this tool with dune 3.x.

**Comment by moyodiallo** [comment]
Yes, that is the purpose. we're going to use this branch https://github.com/moyodiallo/dune.git#opam-dune-lint-testing, to test it on our CI https://github.com/ocurrent/ocaml-ci/pull/811.

**Comment by smorimoto** [comment]
Do you have any plans to upstream changes to this repository?

**Comment by moyodiallo** [comment]
> Do you have any plans to upstream changes to this repository?

Yes, https://github.com/ocurrent/opam-dune-lint/pull/46#issuecomment-1582851187

**Comment by tmcgilchrist** [comment]
This also needs a new release to opam-repository @moyodiallo when dune support is in place.

**Comment by moyodiallo** [comment]
There is a new release now `v0.3`. This can be closed, thanks everyone for the effort.

**Comment by smorimoto** [comment]
Fantastic!

**Comment by tmcgilchrist** [comment]
As always @smorimoto please report any issue found to this repo.
