### ISSUE TITLE
dune language check doesn't match dune version

### ISSUE THREAD

**Issue by Khady** [ocurrent/opam-dune-lint#47]
I'm trying to use the `lint-opam` check provided by setup-ocaml. It seems to run `opam-dune-lint`. And somehow even if dune 3.6.2 is installed, `(lang dune 3.6)` gets rejected

https://github.com/Khady/modern-ocaml/actions/runs/4145135849/jobs/7169100839

```
/opt/hostedtoolcache/opam/2.1.4/x86_64/opam exec -- opam-dune-lint
File "dune-project", line 1, characters 11-14:
1 | (lang dune 3.6)
               ^^^
Error: Version 3.6 of the dune language is not supported.
Supported versions of this extension in version 3.6 of the dune language:
- 1.0 to 1.12
- 2.0 to 2.9
opam-dune-lint: internal error, uncaught exception:
                Failure("run ['dune' 'build' '@install']: exited with 1")
```

**Comment by talex5** [comment]
The logs say:
```
downgrade dune                3.6.2 to 2.9.3 [required by opam-dune-lint]
```

**Comment by talex5** [comment]
(there's some work to add support to dune 3 - see https://github.com/ocurrent/opam-dune-lint/pull/46)

**Comment by Khady** [comment]
ah I missed that part of the logs, thanks
