### ISSUE TITLE
opam-dune-lint suggest to add test dependencies to packages with no tests

### ISSUE THREAD

**Issue by MisterDA** [ocurrent/opam-dune-lint#48]
This is the output of opam-dune-lint on [ocurrent/ocaml-dockerfile](https://github.com/ocurrent/ocaml-dockerfile):
```
/src: (run (shell "opam exec -- opam-dune-lint"))
dockerfile-cmd.opam: changes needed:
  "alcotest" {with-test & >= "1.7.0"}      [from test]
dockerfile-opam.opam: changes needed:
  "alcotest" {with-test & >= "1.7.0"}      [from test]
dockerfile.opam: OK
Note: version numbers are just suggestions based on the currently installed version.
Run with -f to apply changes in non-interactive mode.
"/bin/bash" "-c" "opam exec -- opam-dune-lint" failed with exit status 1
```
It suggests to add the dependency on alcotest to `dockerfile-cmd` and `dockerfile-opam`. The problem is that my dune file only attaches tests to the `dockerfile` package. I think that opam-dune-lint might not be respecting that.
```
(test
 (name dockerfile)
 (package dockerfile)
 (libraries alcotest dockerfile))
```

**Comment by talex5** [comment]
Is this using the main branch, or the #46 PR?

**Comment by MisterDA** [comment]
I suppose it's using the new PR, since I've seen this error with ocaml-ci.
https://ocaml.ci.dev/github/ocurrent/ocaml-dockerfile/commit/5cba26a074eea21708ea9d25ca2f988d80073a7b/variant/%28lint-opam%29

**Comment by moyodiallo** [comment]
Thanks for the report. It is right and it will be address in the PR #46 . Keeping in mind, this is just an experiment to find more bugs.

**Comment by moyodiallo** [comment]
`dune describe external-lib-deps` was giving `(package ())` instead of `(package dockerfile)`:
```  (tests
   ((names (dockerfile))
    (extensions (.exe))
    (package ())
    (source_dir test)
    (external_deps ((alcotest required)))
    (internal_deps ((dockerfile required)))))))
```

It's fixed https://github.com/moyodiallo/dune/commit/118317d305dc2542eb797ff02ae8df42878bf6cd for the CI tests. A fix will be addressed on https://github.com/ocaml/dune.
