### ISSUE TITLE
I have felt the need for this

### ISSUE THREAD

**Issue by UnixJunkie** [ocurrent/opam-dune-lint#5]
But, I feel either dune or opam should do this.
E.g. dune can generate the opam file I think; hence it should be able to check
the consistency of an existing one.

Yet another tool is not going to make our build ecosystem simpler...

**Comment by talex5** [comment]
Many projects don't use dune's opam generation feature, but we still need to check their opam files in CI.

If this works and if dune wants to include similar functionality, it's welcome to it. But I suspect the dependency on the opam libraries may be a hard sell...

**Comment by UnixJunkie** [comment]
If it's hard to add to dune, maybe it means it should be supported by opam then.
An opam project using dune should be able to check the dune file is coherent with the opam file.

**Comment by avsm** [comment]
The longer term plan is to turn `opam lint` into a plugin, at which point it becomes easier to extend and integrate functionality such as this.  For now, this tool solves the immediate problem without requiring anyone to wait on an opam release.
