### ISSUE TITLE
Failure("No *.opam files found!") in a project with a single opam file

### ISSUE THREAD

**Issue by reynir** [ocurrent/opam-dune-lint#51]
I discovered the above exception in an ocaml-ci job:
https://ocaml.ci.dev/github/robur-coop/miragevpn/commit/b2c9e0d177fbf30c727f0e5d401489062c239487/variant/%28lint-opam%29

I have not heard of opam-dune-lint before, and I am not sure what exactly it does or why it claims there are no *.opam files.

**Comment by reynir** [comment]
The error seems due to opam-dune-lint getting packages from dune-project by looking for sexps `(package .. (name xyz) ..)` and the dune-project in question is just `(lang dune 1.0)(name miragevpn)`:

https://github.com/ocurrent/opam-dune-lint/blob/d96423160e9e14db2ab16100d54af51d93e98b93/dune_project.ml#L103-L113

The resulting empty list of packages is used to remove all *.opam files to prevent `dune describe opam-files` (which it doesn't with dune 3.10.0):
https://github.com/ocurrent/opam-dune-lint/blob/d96423160e9e14db2ab16100d54af51d93e98b93/main.ml#L156-L162

**Comment by moyodiallo** [comment]
Thanks for the report and the explanation. We got a fix now #52.
