### ISSUE TITLE
illegal escape sequence

### ISSUE THREAD

**Issue by smorimoto** [ocurrent/opam-dune-lint#68]
Attempting to run this tool on this revision of the lwt repository will cause an error.
https://github.com/ocsigen/lwt/tree/73f1a0f0acd5540f25e58bc410e1f63271189c6c

CI log: https://github.com/ocsigen/lwt/actions/runs/8684977829/job/23813522653?pr=1009

**Comment by smorimoto** [comment]
This commit fixes the issue: https://github.com/ocsigen/lwt/pull/1009/commits/3d519da6e830d8f6e7de565ef02bb4ea1bec5196

**Comment by smorimoto** [comment]
`"%{conf-libev:installed}%"` should be a valid one, but for some reason this tool can't handle it.

**Comment by talex5** [comment]
Looks like when opam-dune-lint loads the opam file, it reads
```
  ["dune" "exec" "-p" name "src/unix/config/discover.exe" "--" "--save"
    "--use-libev" "%{conf-libev:installed}%"]
```
as
```
  ["dune" "exec" "-p" name "src/unix/config/discover.exe" "--" "--save"
    "--use-libev" "\%{conf-libev:installed}%"]
```

The escape seems to be added by `dune describe opam-files`.

**Comment by smorimoto** [comment]
To me, this sounds like a issue to be fixed on this repository side. Is that correct?

**Comment by talex5** [comment]
No, I think this is a bug in opam-dune-lint. There's a disagreement about how escaping works in S-expressions between it and dune. `opam lint` can read the original file OK.

**Comment by smorimoto** [comment]
Oh, I meant opam-dune-lint. Keep this CI job disabled until the fix becomes available.

**Comment by moyodiallo** [comment]
`dune describe opam-files` is used to compare the new and old version of the opam files, to see whether the dependencies have changed.

I have tried `OpamFile.OPAM.read_from_string` on
```
  ["dune" "exec" "-p" name "src/unix/config/discover.exe" "--" "--save"
    "--use-libev" "\%{conf-libev:installed}%"]
```
it is also failing. The result of `dune describe opam-files` is supposed to be compatible with Opam. I think it is better have a fix in Dune.

**Comment by moyodiallo** [comment]
> No, I think this is a bug in opam-dune-lint. There's a disagreement about how escaping works in S-expressions between it and dune. `opam lint` can read the original file OK.

I've just noticed the error is coming from `OpamFile.OPAM.read_from_string` as described on the previous comment, S-expressions are fine.

**Comment by moyodiallo** [comment]
> No, I think this is a bug in opam-dune-lint. There's a disagreement about how escaping works in S-expressions between it and dune. `opam lint` can read the original file OK.

You're right, `dune describe opam-files` escape `%{` when printing it.

**Comment by moyodiallo** [comment]
@smorimoto Thanks for the report, the new release(v0.6) include the fix.

**Comment by smorimoto** [comment]
Thanks a lot!
